// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYjFkyt5n7PbfcFvSXXvMF8-QxaNeIF40',
    appId: '1:521120097255:web:6e9c71700f8748a9635342',
    messagingSenderId: '521120097255',
    projectId: 'vet-clinic-system-9dcc8',
    authDomain: 'vet-clinic-system-9dcc8.firebaseapp.com',
    storageBucket: 'vet-clinic-system-9dcc8.firebasestorage.app',
    measurementId: 'G-KMNL6E6H8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZXtjULBuhW6ZDUZfCbdzel-YmObX8bmg',
    appId: '1:521120097255:android:774ce543c79451bc635342',
    messagingSenderId: '521120097255',
    projectId: 'vet-clinic-system-9dcc8',
    storageBucket: 'vet-clinic-system-9dcc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8XhopYZRpNgeBtz8_eQ525XclZzy507I',
    appId: '1:521120097255:ios:3323d2395c48f249635342',
    messagingSenderId: '521120097255',
    projectId: 'vet-clinic-system-9dcc8',
    storageBucket: 'vet-clinic-system-9dcc8.firebasestorage.app',
    iosBundleId: 'com.example.veterinaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8XhopYZRpNgeBtz8_eQ525XclZzy507I',
    appId: '1:521120097255:ios:3323d2395c48f249635342',
    messagingSenderId: '521120097255',
    projectId: 'vet-clinic-system-9dcc8',
    storageBucket: 'vet-clinic-system-9dcc8.firebasestorage.app',
    iosBundleId: 'com.example.veterinaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYjFkyt5n7PbfcFvSXXvMF8-QxaNeIF40',
    appId: '1:521120097255:web:f7c05f395c2a3421635342',
    messagingSenderId: '521120097255',
    projectId: 'vet-clinic-system-9dcc8',
    authDomain: 'vet-clinic-system-9dcc8.firebaseapp.com',
    storageBucket: 'vet-clinic-system-9dcc8.firebasestorage.app',
    measurementId: 'G-F73XB57BC2',
  );
}
